### ISSUE TITLE
Bug pour le script bg 

### ISSUE THREAD

**Issue by TheBdouilleur2** [TheBdouilleur/powerclip#1]
Lorsque je lance le script background, python me retourne ça:
```
Traceback (most recent call last):
  File "/home/jcode/Bdouilleur_space/Missions in python/powerclip/powerclip_bg.py", line 6, in <module>
    import pystray
  File "/home/jcode/.local/lib/python3.8/site-packages/pystray/__init__.py", line 48, in <module>
    Icon = backend().Icon
  File "/home/jcode/.local/lib/python3.8/site-packages/pystray/__init__.py", line 40, in backend
    return importlib.import_module(__package__ + '._' + module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/jcode/.local/lib/python3.8/site-packages/pystray/_appindicator.py", line 19, in <module>
    gi.require_version('Gtk', '3.0')
AttributeError: module 'gi' has no attribute 'require_version'
```

**Comment by TheBdouilleur** [comment]
Bizarre... c'est à cause du module qui mets une icone dans la barre d'état du système.
Dans tous les cas, je pense que je vais utiliser la fonction intégrée à Qt pour l'icone, c'est mieux.
